# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/afranzin/EMILI5/git

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/afranzin/EMILI5/git

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/afranzin/EMILI5/git/CMakeFiles /home/afranzin/EMILI5/git/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/afranzin/EMILI5/git/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named emili

# Build rule for target.
emili: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emili
.PHONY : emili

# fast build rule for target.
emili/fast:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/build
.PHONY : emili/fast

QAP/qap.o: QAP/qap.cpp.o
.PHONY : QAP/qap.o

# target to build an object file
QAP/qap.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qap.cpp.o
.PHONY : QAP/qap.cpp.o

QAP/qap.i: QAP/qap.cpp.i
.PHONY : QAP/qap.i

# target to preprocess a source file
QAP/qap.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qap.cpp.i
.PHONY : QAP/qap.cpp.i

QAP/qap.s: QAP/qap.cpp.s
.PHONY : QAP/qap.s

# target to generate assembly for a file
QAP/qap.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qap.cpp.s
.PHONY : QAP/qap.cpp.s

QAP/qapBuilder.o: QAP/qapBuilder.cpp.o
.PHONY : QAP/qapBuilder.o

# target to build an object file
QAP/qapBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapBuilder.cpp.o
.PHONY : QAP/qapBuilder.cpp.o

QAP/qapBuilder.i: QAP/qapBuilder.cpp.i
.PHONY : QAP/qapBuilder.i

# target to preprocess a source file
QAP/qapBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapBuilder.cpp.i
.PHONY : QAP/qapBuilder.cpp.i

QAP/qapBuilder.s: QAP/qapBuilder.cpp.s
.PHONY : QAP/qapBuilder.s

# target to generate assembly for a file
QAP/qapBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapBuilder.cpp.s
.PHONY : QAP/qapBuilder.cpp.s

QAP/qapinstance.o: QAP/qapinstance.cpp.o
.PHONY : QAP/qapinstance.o

# target to build an object file
QAP/qapinstance.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapinstance.cpp.o
.PHONY : QAP/qapinstance.cpp.o

QAP/qapinstance.i: QAP/qapinstance.cpp.i
.PHONY : QAP/qapinstance.i

# target to preprocess a source file
QAP/qapinstance.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapinstance.cpp.i
.PHONY : QAP/qapinstance.cpp.i

QAP/qapinstance.s: QAP/qapinstance.cpp.s
.PHONY : QAP/qapinstance.s

# target to generate assembly for a file
QAP/qapinstance.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapinstance.cpp.s
.PHONY : QAP/qapinstance.cpp.s

QAP/qapneighborhood.o: QAP/qapneighborhood.cpp.o
.PHONY : QAP/qapneighborhood.o

# target to build an object file
QAP/qapneighborhood.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapneighborhood.cpp.o
.PHONY : QAP/qapneighborhood.cpp.o

QAP/qapneighborhood.i: QAP/qapneighborhood.cpp.i
.PHONY : QAP/qapneighborhood.i

# target to preprocess a source file
QAP/qapneighborhood.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapneighborhood.cpp.i
.PHONY : QAP/qapneighborhood.cpp.i

QAP/qapneighborhood.s: QAP/qapneighborhood.cpp.s
.PHONY : QAP/qapneighborhood.s

# target to generate assembly for a file
QAP/qapneighborhood.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapneighborhood.cpp.s
.PHONY : QAP/qapneighborhood.cpp.s

QAP/qapsolution.o: QAP/qapsolution.cpp.o
.PHONY : QAP/qapsolution.o

# target to build an object file
QAP/qapsolution.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapsolution.cpp.o
.PHONY : QAP/qapsolution.cpp.o

QAP/qapsolution.i: QAP/qapsolution.cpp.i
.PHONY : QAP/qapsolution.i

# target to preprocess a source file
QAP/qapsolution.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapsolution.cpp.i
.PHONY : QAP/qapsolution.cpp.i

QAP/qapsolution.s: QAP/qapsolution.cpp.s
.PHONY : QAP/qapsolution.s

# target to generate assembly for a file
QAP/qapsolution.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/QAP/qapsolution.cpp.s
.PHONY : QAP/qapsolution.cpp.s

SA/metropolis.o: SA/metropolis.cpp.o
.PHONY : SA/metropolis.o

# target to build an object file
SA/metropolis.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/metropolis.cpp.o
.PHONY : SA/metropolis.cpp.o

SA/metropolis.i: SA/metropolis.cpp.i
.PHONY : SA/metropolis.i

# target to preprocess a source file
SA/metropolis.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/metropolis.cpp.i
.PHONY : SA/metropolis.cpp.i

SA/metropolis.s: SA/metropolis.cpp.s
.PHONY : SA/metropolis.s

# target to generate assembly for a file
SA/metropolis.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/metropolis.cpp.s
.PHONY : SA/metropolis.cpp.s

SA/sa.o: SA/sa.cpp.o
.PHONY : SA/sa.o

# target to build an object file
SA/sa.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa.cpp.o
.PHONY : SA/sa.cpp.o

SA/sa.i: SA/sa.cpp.i
.PHONY : SA/sa.i

# target to preprocess a source file
SA/sa.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa.cpp.i
.PHONY : SA/sa.cpp.i

SA/sa.s: SA/sa.cpp.s
.PHONY : SA/sa.s

# target to generate assembly for a file
SA/sa.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa.cpp.s
.PHONY : SA/sa.cpp.s

SA/saBuilder.o: SA/saBuilder.cpp.o
.PHONY : SA/saBuilder.o

# target to build an object file
SA/saBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/saBuilder.cpp.o
.PHONY : SA/saBuilder.cpp.o

SA/saBuilder.i: SA/saBuilder.cpp.i
.PHONY : SA/saBuilder.i

# target to preprocess a source file
SA/saBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/saBuilder.cpp.i
.PHONY : SA/saBuilder.cpp.i

SA/saBuilder.s: SA/saBuilder.cpp.s
.PHONY : SA/saBuilder.s

# target to generate assembly for a file
SA/saBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/saBuilder.cpp.s
.PHONY : SA/saBuilder.cpp.s

SA/sa_acceptance_criteria.o: SA/sa_acceptance_criteria.cpp.o
.PHONY : SA/sa_acceptance_criteria.o

# target to build an object file
SA/sa_acceptance_criteria.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_acceptance_criteria.cpp.o
.PHONY : SA/sa_acceptance_criteria.cpp.o

SA/sa_acceptance_criteria.i: SA/sa_acceptance_criteria.cpp.i
.PHONY : SA/sa_acceptance_criteria.i

# target to preprocess a source file
SA/sa_acceptance_criteria.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_acceptance_criteria.cpp.i
.PHONY : SA/sa_acceptance_criteria.cpp.i

SA/sa_acceptance_criteria.s: SA/sa_acceptance_criteria.cpp.s
.PHONY : SA/sa_acceptance_criteria.s

# target to generate assembly for a file
SA/sa_acceptance_criteria.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_acceptance_criteria.cpp.s
.PHONY : SA/sa_acceptance_criteria.cpp.s

SA/sa_exploration.o: SA/sa_exploration.cpp.o
.PHONY : SA/sa_exploration.o

# target to build an object file
SA/sa_exploration.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_exploration.cpp.o
.PHONY : SA/sa_exploration.cpp.o

SA/sa_exploration.i: SA/sa_exploration.cpp.i
.PHONY : SA/sa_exploration.i

# target to preprocess a source file
SA/sa_exploration.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_exploration.cpp.i
.PHONY : SA/sa_exploration.cpp.i

SA/sa_exploration.s: SA/sa_exploration.cpp.s
.PHONY : SA/sa_exploration.s

# target to generate assembly for a file
SA/sa_exploration.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_exploration.cpp.s
.PHONY : SA/sa_exploration.cpp.s

SA/sa_neighborhood.o: SA/sa_neighborhood.cpp.o
.PHONY : SA/sa_neighborhood.o

# target to build an object file
SA/sa_neighborhood.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_neighborhood.cpp.o
.PHONY : SA/sa_neighborhood.cpp.o

SA/sa_neighborhood.i: SA/sa_neighborhood.cpp.i
.PHONY : SA/sa_neighborhood.i

# target to preprocess a source file
SA/sa_neighborhood.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_neighborhood.cpp.i
.PHONY : SA/sa_neighborhood.cpp.i

SA/sa_neighborhood.s: SA/sa_neighborhood.cpp.s
.PHONY : SA/sa_neighborhood.s

# target to generate assembly for a file
SA/sa_neighborhood.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_neighborhood.cpp.s
.PHONY : SA/sa_neighborhood.cpp.s

SA/sa_pfsp_parser.o: SA/sa_pfsp_parser.cpp.o
.PHONY : SA/sa_pfsp_parser.o

# target to build an object file
SA/sa_pfsp_parser.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_pfsp_parser.cpp.o
.PHONY : SA/sa_pfsp_parser.cpp.o

SA/sa_pfsp_parser.i: SA/sa_pfsp_parser.cpp.i
.PHONY : SA/sa_pfsp_parser.i

# target to preprocess a source file
SA/sa_pfsp_parser.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_pfsp_parser.cpp.i
.PHONY : SA/sa_pfsp_parser.cpp.i

SA/sa_pfsp_parser.s: SA/sa_pfsp_parser.cpp.s
.PHONY : SA/sa_pfsp_parser.s

# target to generate assembly for a file
SA/sa_pfsp_parser.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_pfsp_parser.cpp.s
.PHONY : SA/sa_pfsp_parser.cpp.s

SA/sa_qap_parser.o: SA/sa_qap_parser.cpp.o
.PHONY : SA/sa_qap_parser.o

# target to build an object file
SA/sa_qap_parser.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_qap_parser.cpp.o
.PHONY : SA/sa_qap_parser.cpp.o

SA/sa_qap_parser.i: SA/sa_qap_parser.cpp.i
.PHONY : SA/sa_qap_parser.i

# target to preprocess a source file
SA/sa_qap_parser.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_qap_parser.cpp.i
.PHONY : SA/sa_qap_parser.cpp.i

SA/sa_qap_parser.s: SA/sa_qap_parser.cpp.s
.PHONY : SA/sa_qap_parser.s

# target to generate assembly for a file
SA/sa_qap_parser.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_qap_parser.cpp.s
.PHONY : SA/sa_qap_parser.cpp.s

SA/sa_termination_criteria.o: SA/sa_termination_criteria.cpp.o
.PHONY : SA/sa_termination_criteria.o

# target to build an object file
SA/sa_termination_criteria.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_termination_criteria.cpp.o
.PHONY : SA/sa_termination_criteria.cpp.o

SA/sa_termination_criteria.i: SA/sa_termination_criteria.cpp.i
.PHONY : SA/sa_termination_criteria.i

# target to preprocess a source file
SA/sa_termination_criteria.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_termination_criteria.cpp.i
.PHONY : SA/sa_termination_criteria.cpp.i

SA/sa_termination_criteria.s: SA/sa_termination_criteria.cpp.s
.PHONY : SA/sa_termination_criteria.s

# target to generate assembly for a file
SA/sa_termination_criteria.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/SA/sa_termination_criteria.cpp.s
.PHONY : SA/sa_termination_criteria.cpp.s

TSP/tsp.o: TSP/tsp.cpp.o
.PHONY : TSP/tsp.o

# target to build an object file
TSP/tsp.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tsp.cpp.o
.PHONY : TSP/tsp.cpp.o

TSP/tsp.i: TSP/tsp.cpp.i
.PHONY : TSP/tsp.i

# target to preprocess a source file
TSP/tsp.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tsp.cpp.i
.PHONY : TSP/tsp.cpp.i

TSP/tsp.s: TSP/tsp.cpp.s
.PHONY : TSP/tsp.s

# target to generate assembly for a file
TSP/tsp.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tsp.cpp.s
.PHONY : TSP/tsp.cpp.s

TSP/tspBuilder.o: TSP/tspBuilder.cpp.o
.PHONY : TSP/tspBuilder.o

# target to build an object file
TSP/tspBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspBuilder.cpp.o
.PHONY : TSP/tspBuilder.cpp.o

TSP/tspBuilder.i: TSP/tspBuilder.cpp.i
.PHONY : TSP/tspBuilder.i

# target to preprocess a source file
TSP/tspBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspBuilder.cpp.i
.PHONY : TSP/tspBuilder.cpp.i

TSP/tspBuilder.s: TSP/tspBuilder.cpp.s
.PHONY : TSP/tspBuilder.s

# target to generate assembly for a file
TSP/tspBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspBuilder.cpp.s
.PHONY : TSP/tspBuilder.cpp.s

TSP/tspinstance.o: TSP/tspinstance.cpp.o
.PHONY : TSP/tspinstance.o

# target to build an object file
TSP/tspinstance.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspinstance.cpp.o
.PHONY : TSP/tspinstance.cpp.o

TSP/tspinstance.i: TSP/tspinstance.cpp.i
.PHONY : TSP/tspinstance.i

# target to preprocess a source file
TSP/tspinstance.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspinstance.cpp.i
.PHONY : TSP/tspinstance.cpp.i

TSP/tspinstance.s: TSP/tspinstance.cpp.s
.PHONY : TSP/tspinstance.s

# target to generate assembly for a file
TSP/tspinstance.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspinstance.cpp.s
.PHONY : TSP/tspinstance.cpp.s

TSP/tspneighborhood.o: TSP/tspneighborhood.cpp.o
.PHONY : TSP/tspneighborhood.o

# target to build an object file
TSP/tspneighborhood.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspneighborhood.cpp.o
.PHONY : TSP/tspneighborhood.cpp.o

TSP/tspneighborhood.i: TSP/tspneighborhood.cpp.i
.PHONY : TSP/tspneighborhood.i

# target to preprocess a source file
TSP/tspneighborhood.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspneighborhood.cpp.i
.PHONY : TSP/tspneighborhood.cpp.i

TSP/tspneighborhood.s: TSP/tspneighborhood.cpp.s
.PHONY : TSP/tspneighborhood.s

# target to generate assembly for a file
TSP/tspneighborhood.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspneighborhood.cpp.s
.PHONY : TSP/tspneighborhood.cpp.s

TSP/tspsolution.o: TSP/tspsolution.cpp.o
.PHONY : TSP/tspsolution.o

# target to build an object file
TSP/tspsolution.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspsolution.cpp.o
.PHONY : TSP/tspsolution.cpp.o

TSP/tspsolution.i: TSP/tspsolution.cpp.i
.PHONY : TSP/tspsolution.i

# target to preprocess a source file
TSP/tspsolution.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspsolution.cpp.i
.PHONY : TSP/tspsolution.cpp.i

TSP/tspsolution.s: TSP/tspsolution.cpp.s
.PHONY : TSP/tspsolution.s

# target to generate assembly for a file
TSP/tspsolution.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/TSP/tspsolution.cpp.s
.PHONY : TSP/tspsolution.cpp.s

emilibase.o: emilibase.cpp.o
.PHONY : emilibase.o

# target to build an object file
emilibase.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/emilibase.cpp.o
.PHONY : emilibase.cpp.o

emilibase.i: emilibase.cpp.i
.PHONY : emilibase.i

# target to preprocess a source file
emilibase.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/emilibase.cpp.i
.PHONY : emilibase.cpp.i

emilibase.s: emilibase.cpp.s
.PHONY : emilibase.s

# target to generate assembly for a file
emilibase.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/emilibase.cpp.s
.PHONY : emilibase.cpp.s

generalParser.o: generalParser.cpp.o
.PHONY : generalParser.o

# target to build an object file
generalParser.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/generalParser.cpp.o
.PHONY : generalParser.cpp.o

generalParser.i: generalParser.cpp.i
.PHONY : generalParser.i

# target to preprocess a source file
generalParser.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/generalParser.cpp.i
.PHONY : generalParser.cpp.i

generalParser.s: generalParser.cpp.s
.PHONY : generalParser.s

# target to generate assembly for a file
generalParser.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/generalParser.cpp.s
.PHONY : generalParser.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/main.cpp.s
.PHONY : main.cpp.s

pfsp/paramsparser.o: pfsp/paramsparser.cpp.o
.PHONY : pfsp/paramsparser.o

# target to build an object file
pfsp/paramsparser.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/paramsparser.cpp.o
.PHONY : pfsp/paramsparser.cpp.o

pfsp/paramsparser.i: pfsp/paramsparser.cpp.i
.PHONY : pfsp/paramsparser.i

# target to preprocess a source file
pfsp/paramsparser.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/paramsparser.cpp.i
.PHONY : pfsp/paramsparser.cpp.i

pfsp/paramsparser.s: pfsp/paramsparser.cpp.s
.PHONY : pfsp/paramsparser.s

# target to generate assembly for a file
pfsp/paramsparser.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/paramsparser.cpp.s
.PHONY : pfsp/paramsparser.cpp.s

pfsp/permutationflowshop.o: pfsp/permutationflowshop.cpp.o
.PHONY : pfsp/permutationflowshop.o

# target to build an object file
pfsp/permutationflowshop.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/permutationflowshop.cpp.o
.PHONY : pfsp/permutationflowshop.cpp.o

pfsp/permutationflowshop.i: pfsp/permutationflowshop.cpp.i
.PHONY : pfsp/permutationflowshop.i

# target to preprocess a source file
pfsp/permutationflowshop.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/permutationflowshop.cpp.i
.PHONY : pfsp/permutationflowshop.cpp.i

pfsp/permutationflowshop.s: pfsp/permutationflowshop.cpp.s
.PHONY : pfsp/permutationflowshop.s

# target to generate assembly for a file
pfsp/permutationflowshop.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/permutationflowshop.cpp.s
.PHONY : pfsp/permutationflowshop.cpp.s

pfsp/pf_instace_generator.o: pfsp/pf_instace_generator.cpp.o
.PHONY : pfsp/pf_instace_generator.o

# target to build an object file
pfsp/pf_instace_generator.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pf_instace_generator.cpp.o
.PHONY : pfsp/pf_instace_generator.cpp.o

pfsp/pf_instace_generator.i: pfsp/pf_instace_generator.cpp.i
.PHONY : pfsp/pf_instace_generator.i

# target to preprocess a source file
pfsp/pf_instace_generator.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pf_instace_generator.cpp.i
.PHONY : pfsp/pf_instace_generator.cpp.i

pfsp/pf_instace_generator.s: pfsp/pf_instace_generator.cpp.s
.PHONY : pfsp/pf_instace_generator.s

# target to generate assembly for a file
pfsp/pf_instace_generator.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pf_instace_generator.cpp.s
.PHONY : pfsp/pf_instace_generator.cpp.s

pfsp/pfspBuilder.o: pfsp/pfspBuilder.cpp.o
.PHONY : pfsp/pfspBuilder.o

# target to build an object file
pfsp/pfspBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pfspBuilder.cpp.o
.PHONY : pfsp/pfspBuilder.cpp.o

pfsp/pfspBuilder.i: pfsp/pfspBuilder.cpp.i
.PHONY : pfsp/pfspBuilder.i

# target to preprocess a source file
pfsp/pfspBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pfspBuilder.cpp.i
.PHONY : pfsp/pfspBuilder.cpp.i

pfsp/pfspBuilder.s: pfsp/pfspBuilder.cpp.s
.PHONY : pfsp/pfspBuilder.s

# target to generate assembly for a file
pfsp/pfspBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pfspBuilder.cpp.s
.PHONY : pfsp/pfspBuilder.cpp.s

pfsp/pfspinstance.o: pfsp/pfspinstance.cpp.o
.PHONY : pfsp/pfspinstance.o

# target to build an object file
pfsp/pfspinstance.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pfspinstance.cpp.o
.PHONY : pfsp/pfspinstance.cpp.o

pfsp/pfspinstance.i: pfsp/pfspinstance.cpp.i
.PHONY : pfsp/pfspinstance.i

# target to preprocess a source file
pfsp/pfspinstance.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pfspinstance.cpp.i
.PHONY : pfsp/pfspinstance.cpp.i

pfsp/pfspinstance.s: pfsp/pfspinstance.cpp.s
.PHONY : pfsp/pfspinstance.s

# target to generate assembly for a file
pfsp/pfspinstance.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/pfsp/pfspinstance.cpp.s
.PHONY : pfsp/pfspinstance.cpp.s

stats/stats_bi.o: stats/stats_bi.cpp.o
.PHONY : stats/stats_bi.o

# target to build an object file
stats/stats_bi.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_bi.cpp.o
.PHONY : stats/stats_bi.cpp.o

stats/stats_bi.i: stats/stats_bi.cpp.i
.PHONY : stats/stats_bi.i

# target to preprocess a source file
stats/stats_bi.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_bi.cpp.i
.PHONY : stats/stats_bi.cpp.i

stats/stats_bi.s: stats/stats_bi.cpp.s
.PHONY : stats/stats_bi.s

# target to generate assembly for a file
stats/stats_bi.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_bi.cpp.s
.PHONY : stats/stats_bi.cpp.s

stats/stats_builder.o: stats/stats_builder.cpp.o
.PHONY : stats/stats_builder.o

# target to build an object file
stats/stats_builder.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_builder.cpp.o
.PHONY : stats/stats_builder.cpp.o

stats/stats_builder.i: stats/stats_builder.cpp.i
.PHONY : stats/stats_builder.i

# target to preprocess a source file
stats/stats_builder.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_builder.cpp.i
.PHONY : stats/stats_builder.cpp.i

stats/stats_builder.s: stats/stats_builder.cpp.s
.PHONY : stats/stats_builder.s

# target to generate assembly for a file
stats/stats_builder.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_builder.cpp.s
.PHONY : stats/stats_builder.cpp.s

stats/stats_fi.o: stats/stats_fi.cpp.o
.PHONY : stats/stats_fi.o

# target to build an object file
stats/stats_fi.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_fi.cpp.o
.PHONY : stats/stats_fi.cpp.o

stats/stats_fi.i: stats/stats_fi.cpp.i
.PHONY : stats/stats_fi.i

# target to preprocess a source file
stats/stats_fi.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_fi.cpp.i
.PHONY : stats/stats_fi.cpp.i

stats/stats_fi.s: stats/stats_fi.cpp.s
.PHONY : stats/stats_fi.s

# target to generate assembly for a file
stats/stats_fi.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_fi.cpp.s
.PHONY : stats/stats_fi.cpp.s

stats/stats_fi_2.o: stats/stats_fi_2.cpp.o
.PHONY : stats/stats_fi_2.o

# target to build an object file
stats/stats_fi_2.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_fi_2.cpp.o
.PHONY : stats/stats_fi_2.cpp.o

stats/stats_fi_2.i: stats/stats_fi_2.cpp.i
.PHONY : stats/stats_fi_2.i

# target to preprocess a source file
stats/stats_fi_2.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_fi_2.cpp.i
.PHONY : stats/stats_fi_2.cpp.i

stats/stats_fi_2.s: stats/stats_fi_2.cpp.s
.PHONY : stats/stats_fi_2.s

# target to generate assembly for a file
stats/stats_fi_2.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_fi_2.cpp.s
.PHONY : stats/stats_fi_2.cpp.s

stats/stats_rw.o: stats/stats_rw.cpp.o
.PHONY : stats/stats_rw.o

# target to build an object file
stats/stats_rw.cpp.o:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_rw.cpp.o
.PHONY : stats/stats_rw.cpp.o

stats/stats_rw.i: stats/stats_rw.cpp.i
.PHONY : stats/stats_rw.i

# target to preprocess a source file
stats/stats_rw.cpp.i:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_rw.cpp.i
.PHONY : stats/stats_rw.cpp.i

stats/stats_rw.s: stats/stats_rw.cpp.s
.PHONY : stats/stats_rw.s

# target to generate assembly for a file
stats/stats_rw.cpp.s:
	$(MAKE) -f CMakeFiles/emili.dir/build.make CMakeFiles/emili.dir/stats/stats_rw.cpp.s
.PHONY : stats/stats_rw.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... emili"
	@echo "... rebuild_cache"
	@echo "... QAP/qap.o"
	@echo "... QAP/qap.i"
	@echo "... QAP/qap.s"
	@echo "... QAP/qapBuilder.o"
	@echo "... QAP/qapBuilder.i"
	@echo "... QAP/qapBuilder.s"
	@echo "... QAP/qapinstance.o"
	@echo "... QAP/qapinstance.i"
	@echo "... QAP/qapinstance.s"
	@echo "... QAP/qapneighborhood.o"
	@echo "... QAP/qapneighborhood.i"
	@echo "... QAP/qapneighborhood.s"
	@echo "... QAP/qapsolution.o"
	@echo "... QAP/qapsolution.i"
	@echo "... QAP/qapsolution.s"
	@echo "... SA/metropolis.o"
	@echo "... SA/metropolis.i"
	@echo "... SA/metropolis.s"
	@echo "... SA/sa.o"
	@echo "... SA/sa.i"
	@echo "... SA/sa.s"
	@echo "... SA/saBuilder.o"
	@echo "... SA/saBuilder.i"
	@echo "... SA/saBuilder.s"
	@echo "... SA/sa_acceptance_criteria.o"
	@echo "... SA/sa_acceptance_criteria.i"
	@echo "... SA/sa_acceptance_criteria.s"
	@echo "... SA/sa_exploration.o"
	@echo "... SA/sa_exploration.i"
	@echo "... SA/sa_exploration.s"
	@echo "... SA/sa_neighborhood.o"
	@echo "... SA/sa_neighborhood.i"
	@echo "... SA/sa_neighborhood.s"
	@echo "... SA/sa_pfsp_parser.o"
	@echo "... SA/sa_pfsp_parser.i"
	@echo "... SA/sa_pfsp_parser.s"
	@echo "... SA/sa_qap_parser.o"
	@echo "... SA/sa_qap_parser.i"
	@echo "... SA/sa_qap_parser.s"
	@echo "... SA/sa_termination_criteria.o"
	@echo "... SA/sa_termination_criteria.i"
	@echo "... SA/sa_termination_criteria.s"
	@echo "... TSP/tsp.o"
	@echo "... TSP/tsp.i"
	@echo "... TSP/tsp.s"
	@echo "... TSP/tspBuilder.o"
	@echo "... TSP/tspBuilder.i"
	@echo "... TSP/tspBuilder.s"
	@echo "... TSP/tspinstance.o"
	@echo "... TSP/tspinstance.i"
	@echo "... TSP/tspinstance.s"
	@echo "... TSP/tspneighborhood.o"
	@echo "... TSP/tspneighborhood.i"
	@echo "... TSP/tspneighborhood.s"
	@echo "... TSP/tspsolution.o"
	@echo "... TSP/tspsolution.i"
	@echo "... TSP/tspsolution.s"
	@echo "... emilibase.o"
	@echo "... emilibase.i"
	@echo "... emilibase.s"
	@echo "... generalParser.o"
	@echo "... generalParser.i"
	@echo "... generalParser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pfsp/paramsparser.o"
	@echo "... pfsp/paramsparser.i"
	@echo "... pfsp/paramsparser.s"
	@echo "... pfsp/permutationflowshop.o"
	@echo "... pfsp/permutationflowshop.i"
	@echo "... pfsp/permutationflowshop.s"
	@echo "... pfsp/pf_instace_generator.o"
	@echo "... pfsp/pf_instace_generator.i"
	@echo "... pfsp/pf_instace_generator.s"
	@echo "... pfsp/pfspBuilder.o"
	@echo "... pfsp/pfspBuilder.i"
	@echo "... pfsp/pfspBuilder.s"
	@echo "... pfsp/pfspinstance.o"
	@echo "... pfsp/pfspinstance.i"
	@echo "... pfsp/pfspinstance.s"
	@echo "... stats/stats_bi.o"
	@echo "... stats/stats_bi.i"
	@echo "... stats/stats_bi.s"
	@echo "... stats/stats_builder.o"
	@echo "... stats/stats_builder.i"
	@echo "... stats/stats_builder.s"
	@echo "... stats/stats_fi.o"
	@echo "... stats/stats_fi.i"
	@echo "... stats/stats_fi.s"
	@echo "... stats/stats_fi_2.o"
	@echo "... stats/stats_fi_2.i"
	@echo "... stats/stats_fi_2.s"
	@echo "... stats/stats_rw.o"
	@echo "... stats/stats_rw.i"
	@echo "... stats/stats_rw.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

