#ifndef SA_CONSTANTS_H
#define SA_CONSTANTS_H


/**
 * initial temperature
 */
#define FIXEDINITTEMP "FIXEDINITTEMP"
#define INITFROMSOL   "INITFROMSOL"
#define RANDOMWALKINITTEMP "RANDOMWALKINITTEMP"
#define RANDOMWALKAVGINITTEMP "RANDOMWALKAVGINITTEMP"
#define RANDOMWALKINITPROB "RANDOMWALKINITPROB"


/**
 * acceptance criteria
 */
#define METROPOLIS "METROPOLIS"
#define METROPOLISWFORCED "METROPOLISWFORCED"
#define BASICACC   "BASICACC"
#define GEOMACC    "GEOMACC"
#define DETERMINISTICACC "DETERMINISTICACC"
#define LAHCACC    "LAHCACC"
#define GDAACC     "GDAACC"
#define RTRACC     "RTRACC"
#define APPROXEXPACC "APPROXEXPACC"
#define GENSAACC   "GENSAACC"


/**
 * exploration method
 */
#define SARANDOMEXPLORATION "SARANDOMEXPLORATION"
#define SASEQUENTIALEXPLORATION "SASEQUENTIALEXPLORATION"
#define SAFIRSTIMPROVEMENTEXPLORATION "SAFIRSTIMPROVEMENTEXPLORATION"
#define SABESTIMPROVEMENTEXPLORATION "SABESTIMPROVEMENTEXPLORATION"

/**
 * TempLength
 */
#define CONSTTEMPLEN     "CONSTTEMPLEN"
#define NEIGHSIZETEMPLEN "NEIGHSIZETEMPLEN"
#define MAXACCEPTEDTEMPLEN "MAXACCEPTEDTEMPLEN"
#define ARITMTEMPLEN "ARITMTEMPLEN"
#define GEOMTEMPLEN "GEOMTEMPLEN"
#define LOGTEMPLEN "LOGTEMPLEN"
#define EXPTEMPLEN "EXPTEMPLEN"
#define NOTEMPLEN "NOTEMPLEN"

/**
 * cooling schemes
 */
#define GEOM          "GEOM"
#define MARKOV        "MARKOV"
#define LOGCOOLING    "LOGCOOLING"
#define CONSTCOOLING  "CONSTCOOLING"
#define LUNDYMEES     "LUNDYMEES"
#define LINEARCOOLING "LINEARCOOLING"
#define TEMPBANDCOOLING "TEMPBANDCOOLING"
#define QUADRATICCOOLING "QUADRATICCOOLING"
#define Q87COOLING    "Q87COOLING"
#define NOCOOLING     "NOCOOLING"

/**
 * temperature restart
 */
#define SANOTEMPRESTART "SANOTEMPRESTART"
#define SAMINTEMPRESTART "SAMINTEMPRESTART"
#define SAPERCTEMPRESTART "SAPERCTEMPRESTART"
#define SALOWRATERESTART "SALOWRATERESTART"
#define SALASTRATERESTART "SALASTRATERESTART"
#define SALOWRATEREHEAT "SALOWRATEREHEAT"
#define SALASTRATEREHEAT "SALASTRATEREHEAT"
#define SALOCALMINREHEAT "SALOCALMINREHEAT"
#define SALOCALMINENHANCEDREHEAT "SALOCALMINENHANCEDREHEAT"
#define SALOWRATERESTARTBEST "SALOWRATERESTARTBEST"
#define SALOCALMINRESTARTBEST "SALOCALMINRESTARTBEST"

/**
 * termination criteria
 */
#define MAXBADITERS     "MAXBADITERS" 
#define MAXITERS        "MAXITERS"
#define NEVERTERM       "NEVERTERM"
#define ACCRATETERM     "ACCRATETERM"
#define LASTACCRATETERM "LASTACCRATETERM"

#endif
