#!/bin/bash

if [ $# -ne 2 ]
then
    echo "                 ______ __  __ _____ _      _____ "
    echo "                |  ____|  \/  |_   _| |    |_   _|"
    echo "                | |__  | \  / | | | | |      | |  "
    echo "                |  __| | |\/| | | | | |      | |  "
    echo "                | |____| |  | |_| |_| |____ _| |_ "
    echo "                |______|_|  |_|_____|______|_____|"
    echo "                                                  "
    echo " $* "
    echo "                                                  "
    echo "utility to convert configurations from grammar2code format to emili format "
	  echo "Usage: conf_translator.sh grammar candidates_file"
else

OUTPUT="/dev/null"
GRAMMAR2CODE="grammar2code"

FILENAME="$2"
GRAMMAR_DIR="$1"
while read -r line
do

   SOLUTION=${line:2} 
   
   $GRAMMAR2CODE $GRAMMAR_DIR -t . $SOLUTION  1>> $OUTPUT 2>> $OUTPUT
   EMILI_PARAMS=`cat params`
   echo "${line:0:2} ->  $EMILI_PARAMS"
done < "$FILENAME"
yes | rm params
fi
